### ISSUE TITLE
documentserver start failed

### ISSUE THREAD

**Issue by fendaq** [onlyoffice-testing-robot/documentserver-docker-from-manual#28]
```
 * Starting PostgreSQL 10 database server                                [ OK ] 
 * Starting RabbitMQ Messaging Server rabbitmq-server                    [ OK ] 
 * Starting nginx nginx                                                  [ OK ] 
CREATE DATABASE
CREATE ROLE
GRANT
CREATE TABLE
CREATE TABLE
CREATE FUNCTION
mkdir: 无法创建目录"fonts": 文件已存在
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/01_blank.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/02_basic.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/03_classic.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/04_official.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/05_green leaf.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/06_lines.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/07_office.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/08_safari.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/09_dotted.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/10_corner.pptx: <result><error code="calculate" /></result>
Uncaught TypeError: Cannot read property 'WH' of undefined
could not use /out/linux_64/onlyoffice/documentserver/sdkjs/slide/themes/src/11_tort.pptx: <result><error code="calculate" /></result>
root@5ab44b4c8bdb:/out/linux_64/onlyoffice/documentserver/server/DocService# pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: ENOENT: no such file or directory, open '../../Common/config/log4js/development.json'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.openSync (fs.js:498:3)
    at Object.openSync (pkg/prelude/bootstrap.js:796:32)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at loadConfigurationFile (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:49:26)
    at Object.configure (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:58:20)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../../Common/config/log4js/development.json',
  pkg: true
}
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: ENOENT: no such file or directory, open '../../Common/config/log4js/development.json'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.openSync (fs.js:498:3)
    at Object.openSync (pkg/prelude/bootstrap.js:796:32)
    at Object.readFileSync (fs.js:394:35)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
    at loadConfigurationFile (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:49:26)
    at Object.configure (/snapshot/server/build/server/Common/node_modules/log4js/lib/log4js.js:58:20)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '../../Common/config/log4js/development.json',
  pkg: true
}
```

**Comment by ShockwaveNN** [comment]
I think something got wrong during compilation

> Uncaught TypeError: Cannot read property 'WH' of undefined

This is a bad error. Are you using proper latest version of `build_tools`? Which host system did you used to compile it?

**Comment by fendaq** [comment]
last version of build_tools。  ubuntu 18.04 on arch64
This is the compilation log. It seems that I didn't find any obvious errors on it
[session.zip](https://github.com/ONLYOFFICE-QA/onlyoffice-documentserver-run-compiled/files/8752531/session.zip)
，

**Comment by ShockwaveNN** [comment]
@fendaq if by `arch64` you mean `AArch64` - we got separate issue for that https://github.com/ONLYOFFICE/build_tools/issues/470#issuecomment-1134241405

It's for desktopEditors but I think problem are the same

I'm personally never tried to compile aarch64 version, I'm checking it right now, so It can be not fully working as your logs presume

I think it's better to move our discussion to `build_tools` repo, since this particular repo is for QA purposes
